# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

final_space: true
version: 3

palette:
  os: "#ACB0BE"
  closer: "p:os"
  pink: "#F4B8E4"
  lavender: "#BABBF1"
  blue: "#8CAAEE"

blocks:
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: path
        style: plain
        template: "{{ .Path }}"
        foreground: "p:pink"
        properties:
          style: full

      - type: git
        style: plain
        template: "{{ .HEAD }} "
        foreground: "p:lavender"
        properties:
          branch_icon: " "
          cherry_pick_icon: " "
          commit_icon: " "
          fetch_status: false
          fetch_upstream_icon: false
          merge_icon: " "
          no_commits_icon: " "
          rebase_icon: " "
          revert_icon: " "
          tag_icon: " "

  - type: rprompt
    overflow: hidden
    segments:
      - type: executiontime
        style: plain
        foreground: yellow
        background: transparent
        template: "{{ div .Ms 1000 }}s"

  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: text
        style: plain
        foreground_templates:
        ["{{if gt .Code 0}}red{{end}}", "{{if eq .Code 0}}p:blue{{end}}"]
        template: "❯"

transient_prompt:
  foreground_templates:
  ["{{if gt .Code 0}}red{{end}}", "{{if eq .Code 0}}p:blue{{end}}"]
  background: transparent
  template: "❯"

secondary_prompt:
  foreground: "p:blue"
  background: transparent
  template: "❯❯"




